name: CI/CD to staging

on:
  push:
    branches: [ master ]

permissions:
  pull-requests: read
  contents: read
  id-token: write

jobs:
  build_and_test:
    uses: ./.github/workflows/test.yml
  
  build_and_push_docker_image:
    needs: build_and_test
    uses: ./.github/workflows/build-docker.yml
    with:
      PROJECT_ID_ARTIFACT_REGISTRY: vl-bots-common/vl-invoicerbot-stage-repository
      REGION: europe-west1
      SERVICE: invoicerbot-stage
      BUILD_ENV: prod
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER_STAGE }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT_STAGE }}
  
  deploy_to_stage:
    needs: build_and_push_docker_image
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      PROJECT_ID_ARTIFACT_REGISTRY: vl-bots-common/vl-invoicerbot-stage-repository
      SERVICE: invoicerbot-stage
      PROJECT_ID_CLOUD_RUN: vl-bots-invoicerbot-stage
      REGION: europe-west1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER_STAGE }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT_STAGE }}
  