name: CI/CD build Docker image and push to AR

on:
  workflow_call:
    inputs:
      PROJECT_ID_ARTIFACT_REGISTRY:
        required: true
        type: string
      REGION:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
      BUILD_ENV:
        required: true
        type: string
    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true


permissions:
  contents: read
  id-token: write

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth from the pipeline
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Docker Auth to Google Cloud Artifact Registry
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ inputs.REGION }}-docker.pkg.dev"

      - name: Build and Push docker image for
        run: |-
          DOCKER_IMAGE_NAME="${{ inputs.REGION }}-docker.pkg.dev/${{ inputs.PROJECT_ID_ARTIFACT_REGISTRY }}/${{ inputs.SERVICE }}" 
          docker build -t "$DOCKER_IMAGE_NAME:${{ github.sha }}" -t "$DOCKER_IMAGE_NAME:latest" ./ --build-arg BUILD_ENV=${{ inputs.BUILD_ENV }}
          docker push "$DOCKER_IMAGE_NAME" --all-tags          