name: Invoicer CI test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x         
      
      - name: Install dependencies
        run: |-
          npm i -g yarn

      - name: Copy env templates 
        run: |-
          cp .env.template .env

      - name: Install application dependencies
        run: |-
          yarn

      - name: Build application
        run: |- 
          yarn build